% Create a waveguideCircular antenna
% Generated by MATLAB(R) 24.2 and Antenna Toolbox 24.2
%Generated on:07-Nov-2024 00:02:11

%% Antenna Properties 

antennaObject = design(waveguideCircular, 2400*1e6);
antennaObject.Radius = 0.0425;
antennaObject.Height = 0.125;
antennaObject.FeedHeight = 0.0615;
antennaObject.FeedWidth = 0.001;
antennaObject.FeedOffset = 0.0615;
antennaObject.Load.Impedance = 50;
% Show
figure;
show(antennaObject) 

%% Antenna Analysis 
% Define plot frequency 
plotFrequency = 2.4*1e9;
% Define frequency range 
freqRange = [2.4e9]; %(2160:24:2640)*1e6;
% Reference Impedance 
refImpedance = 50;
% impedance
figure;
impedance(antennaObject, freqRange)% sparameter
figure;
s = sparameters(antennaObject, freqRange, refImpedance); 
rfplot(s)% pattern
figure;
pattern(antennaObject, plotFrequency)% azimuth
figure;
patternAzimuth(antennaObject, plotFrequency, 0, 'Azimuth', 0:5:360)% elevation
figure;
patternElevation(antennaObject, plotFrequency,0,'Elevation',0:5:360)

